// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiMeyJlzB_xQaqV7PFo1qwc9v_kCNh8PE',
    appId: '1:438679314110:web:813c39c9ab330669bd88ef',
    messagingSenderId: '438679314110',
    projectId: 'dailyplanner-a8420',
    authDomain: 'dailyplanner-a8420.firebaseapp.com',
    storageBucket: 'dailyplanner-a8420.firebasestorage.app',
    measurementId: 'G-Y71K0P2R78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQfHC4uE3nsRN2yj1rDbRIVxRXR6bQso',
    appId: '1:438679314110:android:13c20532a9a4ae4fbd88ef',
    messagingSenderId: '438679314110',
    projectId: 'dailyplanner-a8420',
    storageBucket: 'dailyplanner-a8420.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiMeyJlzB_xQaqV7PFo1qwc9v_kCNh8PE',
    appId: '1:438679314110:web:fc29460d17eeff51bd88ef',
    messagingSenderId: '438679314110',
    projectId: 'dailyplanner-a8420',
    authDomain: 'dailyplanner-a8420.firebaseapp.com',
    storageBucket: 'dailyplanner-a8420.firebasestorage.app',
    measurementId: 'G-K37VXFVGX9',
  );
}
